# Servidor
##server.port=8080

# PostgreSQL
##spring.datasource.url=jdbc:postgresql://localhost:5432/Policlinico_prueba
##spring.datasource.username=postgres
##spring.datasource.password=tu_contraseña
##spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
##spring.jpa.hibernate.ddl-auto=validate
##spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email (configurar con tus credenciales)
##spring.mail.host=smtp.gmail.com
##spring.mail.port=587
##spring.mail.username=tu_correo@gmail.com
##spring.mail.password=tu_contraseña
##spring.mail.properties.mail.smtp.auth=true
##spring.mail.properties.mail.smtp.starttls.enable=true

# Directorio para guardar boletas PDF
##pdf.storage.path=./boletas


server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Policlinico_prueba
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email CONFIGURACIÓN REAL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=panchopanza64@gmail.com
spring.mail.password=royz ksxw djmh rgbf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Directorio para guardar boletas PDF
pdf.storage.path=./boletas


