# Servidor
##server.port=8080

# PostgreSQL
##spring.datasource.url=jdbc:postgresql://localhost:5432/Policlinico_prueba
##spring.datasource.username=postgres
##spring.datasource.password=tu_contraseña
##spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
##spring.jpa.hibernate.ddl-auto=validate
##spring.jpa.show-sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email (configurar con tus credenciales)
##spring.mail.host=smtp.gmail.com
##spring.mail.port=587
##spring.mail.username=tu_correo@gmail.com
##spring.mail.password=tu_contraseña
##spring.mail.properties.mail.smtp.auth=true
##spring.mail.properties.mail.smtp.starttls.enable=true

# Directorio para guardar boletas PDF
##pdf.storage.path=./boletas


server.port=8080

# Base de datos H2 en memoria (no necesita instalación)
spring.datasource.url=jdbc:h2:mem:policlinica;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA - H2 creará las tablas automáticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Deshabilitar email temporalmente (para pruebas)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=falso@gmail.com
spring.mail.password=falso
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Directorio para guardar boletas PDF
pdf.storage.path=./boletas


